
double FMAX(double a,double b);
double FMIN(double a,double b);
double FABS(double a);
double doRightSmaller(double a,double b);
double doSign(double a);



#define tMaOne (-1)
#define tMaTwo (-2)
#define tMaThree (-3)
#define tMaFour (-4)
#define tMaFive (-5)
#define tMaSix (-6)
#define tMaSeven (-7)
#define tMaEight (-8)
#define tMaNine (-9)
#define tMaTen (-10)
#define tMaEleven (-11)
#define tMaTwelve (-12)
#define tMaThirteen (-13)
#define tMaFourteen (-14)
#define tMaFifteen (-15)
#define tMaSixteen (-16)
#define tMaSeventeen (-17)
#define tMaEighteen (-18)
#define tMaNineteen (-19)
#define tMaTwenty (-20)
#define tMaTwentyOne (-21)
#define tMaTwentyTwo (-22)
#define tMaTwentyThree (-23)
#define tMaTwentyFour (-24)
#define tMaTwentyFive (-25)

#define tPaOne (1)
#define tPaTwo (2)
#define tPaThree (3)
#define tPaFour (4)
#define tPaFive (5)
#define tPaSix (6)
#define tPaSeven (7)
#define tPaEight (8)
#define tPaNine (9)
#define tPaTen (10)
#define tPaEleven (11)
#define tPaTwelve (12)
#define tPaThirteen (13)
#define tPaFourteen (14)
#define tPaFifteen (15)
#define tPaSixteen (16)
#define tPaSeventeen (17)
#define tPaEighteen (18)
#define tPaNineteen (19)
#define tPaTwenty (20)
#define tPaTwentyOne (21)
#define tPaTwentyTwo (22)
#define tPaTwentyThree (23)
#define tPaTwentyFour (24)
#define tPaTwentyFive (25)

